### ISSUE TITLE
Browsing and installing packages?

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/npm-internal#10]
Hey @mick - two questions:

1. What's the best way to check what packages are available?
2. What's the best way to install packages? Is the only way to do this to save the URL npm-internal gives me and use that as the source?

**Comment by mick** [comment]
Hey @samanpwbb sorry I missed this...  if it is at all still relevant:

> What's the best way to check what packages are available?
I just added a command for this: `npm-internal show <package name>`

> What's the best way to install packages? Is the only way to do this to save the URL npm-internal gives me and use that as the source?

Yeah that is currently the best way. Generally just throw that in your package json, and `npm i`
