### ISSUE TITLE
npm-internal publish does not work for scoped packages

### ISSUE THREAD

**Issue by mapsam** [mapbox/npm-internal#29]
running `npm-internal publish` for a scoped module currently fails:

```
Error: ENOENT: no such file or directory, lstat '@org/package-name-1.0.0.tgz'
```

It appears `npm pack` creates a package tgz with the following name: `org-package-name-1.0.0.tgz` instead of creating a new folder called `@org/`. When `s3.putObject` comes along it looks for a packaged module within the `@org/` folder but it doesn't exist. 

It seems like the quickest fix would be to update the expected path for s3 to put, rather than requiring npm to create the actual `@org` folder.

cc @rclark

**Comment by mapsam** [comment]
Looks like npm makes the definite decision to rename the package name here: https://github.com/npm/npm/blob/latest/lib/pack.js#L53-L55

**Comment by rclark** [comment]
> When s3.putObject comes along it looks for a packaged module within the @org/ folder but it doesn't exist.

This definitely sounds like the place that we'll be able to fix. :+1:
